ROW_LIMIT = 5000

SAMPLES_ROW_LIMIT = 100

SUPERSET_WEBSERVER_PORT = 8088

SECRET_KEY='<SUPERSETSECRETKEY>'

#SQLALCHEMY_DATABASE_URI='mssql+pymssql://superset_user:<SUPERSETUSERSQLPASSWORD>@mssql:1433/superset?Encrypt=yes'

