ROW_LIMIT = 5000

SAMPLES_ROW_LIMIT = 100

SUPERSET_WEBSERVER_PORT = 8088

SECRET_KEY='<SUPERSETSECRETKEY>'

SQLALCHEMY_DATABASE_URI='postgresql://superset_user:<SUPERSETUSERPASSWORD>@postgres:5432/superset_metastore'

