FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-utils \
        ca-certificates \
        dialog \
        openjdk-8-jdk \
        socat \
        software-properties-common \
        supervisor \
        unzip \
        wget