FROM mcr.microsoft.com/mssql/server:2019-latest

ARG HIVE_USER_PASSWORD=Supersecretpassw0rd!
ARG SA_PW=MostSecretPW!

ENV SA_PASSWORD=${SA_PW}

USER root

RUN mkdir -p /scripts

COPY templates/sql-scripts/* /scripts

RUN sed -i "s|<HIVEUSERSQLPASSWORD>|${HIVE_USER_PASSWORD}|g" /scripts/init_databases.sql

RUN sed -i "s|<SAPASSWORD>|${SA_PW}|g" /scripts/entrypoint.sh

RUN chmod 777 /scripts

USER mssql

ENTRYPOINT /bin/bash /scripts/entrypoint.sh