FROM mcr.microsoft.com/mssql/server:2019-latest

ARG HIVE_USER_PASSWORD=Supersecretpassw0rd!
ARG SA_PW=MostSecretPW!

ENV SA_PASSWORD=${SA_PW}

USER root

RUN mkdir -p /usr/src/app

COPY templates/sql-scripts/* /usr/src/app

RUN sed -i "s|<HIVEUSERSQLPASSWORD>|${HIVE_USER_PASSWORD}|g" /usr/src/app/init_metastore.sql

RUN sed -i "s|<SAPASSWORD>|${SA_PW}|g" /usr/src/app/entrypoint.sh

USER mssql

ENTRYPOINT /bin/bash /usr/src/app/entrypoint.sh